INSERT IGNORE INTO `items` (`name`, `label`, `limit`, `weight`, `rare`, `can_remove`) 

VALUES 
('icetea', 'Icetea', NULL, '1', '0', '1'),
('cola', 'Coca Cola', NULL, '1', '0', '1'),
('fristi', 'Fristi', NULL, '1', '0', '1'),
('lemonade', 'Limonade', NULL, '1', '0', '1'),
('cupcake', 'Cupcake', NULL, '1', '0', '1'),
('thee', 'Thee', NULL, '1', '0', '1'),
('coffe', 'Koffie', NULL, '1', '0', '1'),
('chickennugget', 'Kipnuggets', NULL, '1', '0', '1'),
('chips2', 'Paprika Chips', NULL, '1', '0', '1'),
('chips1', 'Naturel Chips', NULL, '1', '0', '1'),
('candy', 'Zakje Snoep', NULL, '1', '0', '1'),
('smoothie3', 'Bananen Smoothie', NULL, '1', '0', '1'),
('smoothie2', 'Aardbei Smoothie', NULL, '1', '0', '1'),
('smoothie1', 'Mango Banaan Smoothie', NULL, '1', '0', '1'),
('cake1', 'Koekje', NULL, '1', '0', '1'),
('cake2', 'Smoeltjes', NULL, '1', '0', '1'),
('tosti', 'Ham-Kaas Tosti', NULL, '1', '0', '1'),
('bread2', 'Hotdog', NULL, '1', '0', '1'),
('bread1', 'Broodje Gezond', NULL, '1', '0', '1'),
('fruit1', 'Appel', NULL, '1', '0', '1'),
('fruit2', 'Peer', NULL, '1', '0', '1'),
('donut', 'Donut', NULL, '1', '0', '1'),
('pie', 'Stukje Taart', NULL, '1', '0', '1'),
('fruit3', 'Banaan', NULL, '1', '0', '1'),
('juice', 'juice', NULL, '1', '0', '1'),
('pizza1', 'Pizza Magarita', NULL, '1', '0', '1'),
('pizza2', 'Pizza Hawaii', NULL, '1', '0', '1'),
('chocolate', 'Melk Chocolade Reep', NULL, '1', '0', '1');