INSERT IGNORE INTO `items` (`name`, `label`, `limit`, `weight`, `rare`, `can_remove`) 

VALUES 
('icetea', 'Icetea', NULL, '1', '0', '1'),
('cola', 'Coca Cola', NULL, '1', '0', '1'),
('fristi', 'Fristi', NULL, '1', '0', '1'),
('lemonade', 'Lemonade', NULL, '1', '0', '1'),
('cupcake', 'Cupcake', NULL, '1', '0', '1'),
('thee', 'Thee', NULL, '1', '0', '1'),
('coffe', 'Coffe', NULL, '1', '0', '1'),
('chickennugget', 'Chicken Nuggets', NULL, '1', '0', '1'),
('chips2', 'Paprika Chips', NULL, '1', '0', '1'),
('chips1', 'Natural Chips', NULL, '1', '0', '1'),
('candy', 'Candy', NULL, '1', '0', '1'),
('smoothie3', 'Banana Smoothie', NULL, '1', '0', '1'),
('smoothie2', 'Strawberry Smoothie', NULL, '1', '0', '1'),
('smoothie1', 'Mango Banana Smoothie', NULL, '1', '0', '1'),
('cake1', 'Cakes', NULL, '1', '0', '1'),
('cake2', 'Smoeltjes', NULL, '1', '0', '1'),
('tosti', 'Ham-Cheese Tosti', NULL, '1', '0', '1'),
('bread2', 'Hotdog', NULL, '1', '0', '1'),
('bread1', 'Toast', NULL, '1', '0', '1'),
('fruit1', 'Appel', NULL, '1', '0', '1'),
('fruit2', 'Pear', NULL, '1', '0', '1'),
('donut', 'Donut', NULL, '1', '0', '1'),
('pie', 'Piece of cake', NULL, '1', '0', '1'),
('fruit3', 'Banana', NULL, '1', '0', '1'),
('juice', 'Juice', NULL, '1', '0', '1'),
('pizza1', 'Pizza Magarita', NULL, '1', '0', '1'),
('pizza2', 'Pizza Hawaii', NULL, '1', '0', '1'),
('chocolate', 'Milk Chocolate Reep', NULL, '1', '0', '1');